### PR TITLE
Submission registry

### PR DESCRIPTION
**Pull request by ikostadi**
Hi Marcel,

I integrated the Submission registry into the existing DDL. The only significant differences are in the research object table, I have kept your definition intact with one exception (bigint-->bigserial) and added only what is necessary from my mockup. Let me know what you think.

Best,
Ivo

### CODE REVIEW

**Comment by Marfroem** [comment]
Sorry the function comment was not exact.
We can use the most sql functions over the custom sql option of ServiceBuilder. I prefer a solution where all functions that work on the database are on one system and currently we work only with service builder for functions.

**Comment by Marfroem** [comment]
The primarykey of the Submission Registry can consists of researchobjectId, researchobjectVersion and archiveId, but not archiveLabel because I can't ensure, that is unique

**Comment by ikostadi** [comment]
> * all Gfbio enitties have the prefix gfbio_

OK, I can change my code to adhere to that.

> * need we a function in the sql-script? Basically we stored only the data in the database. The real functions run over the ServiceBilder?

I assume you mean functions like **add_research_object** and **get_submission_history**? In general, I like the idea of putting the API as close to data as possible (without mixing the MVC layers ;). In this particular case I needed to quickly model the way we will interact with the **researchobject** and **submission_registry**. You have a valid point with keeping functions in one place and as long as the functionality is the same (special attention to data integrity) I am fine with that. We can skip the functions here and I will formulate what they do as a requirement for the WS. Triggers and trigger functions obviously belong in the DB.

> * for the entity like Persistent Identifier, Data Provider, I will test a version on HeadColumnContent
> * the primarykey of the Submission Registry can be a problem, because the dataprovider ist a part of HeadColumnContent. I have a solution, but I have to test this.

Let me know how the tests go, but please consider the time frame we agreed on. I am curious to see if and how FK constraint work with the HCC construct. In any case, I still advocate 'normal' tables for these entities.

> * understand I this right? In the Submision Registry archive is the dataprovider label and archive_pid is the dataproviderId?

Sorry, I should have documented this better - **archive** indeed points to the label of the entity **data_provider** , but **archive_pid** is the unique identifier that was assigned to this research object.

**Comment by ikostadi** [comment]
> The primarykey of the Submission Registry can consists of researchobjectId, researchobjectVersion and archiveId, but not archiveLabel because I can't ensure, that is unique

Why not? Since I didn't have the semantic description of the field, I assumed it is a short label which we will provide (and maybe use for representations on the web). I would even suggest that the data_provider entity would benefit from a natural key and label looked like a good candidate (at least to be unique) at the time. We can discuss this in length in a telco. 
Of course we can use the archiveId as the FK. The disadvantage would be that any select on the SubReg would need an additional JOIN to the data_provider table to get the name (not a very big deal).
I assume the ServiceBuilder can deal with natural keys?

**Comment by ikostadi** [comment]
By the way, @Marfroem do you agree with researchobjectId being bigserial?

**Comment by Marfroem** [comment]
In ServiceBuilder we use the type long, so maybe we can get a problem when the bigserial is not height enoth for the id. But this problem is by bigint too.

If we have a real table,  a label is no problem. But with HCC I can't ensure, that is unique over the cellcontent column in the contententity. Ok I can write a custpm-sql-query / sql-function that check this by the build-label, but this need HCC internal some more informations. I think I can build this, but it is nothing for the first steps

**Comment by ikostadi** [comment]
[Java **long**](http://docs.oracle.com/javase/tutorial/java/nutsandbolts/datatypes.html) and [PostgreSQL **bigint**](http://www.postgresql.org/docs/9.4/interactive/datatype-numeric.html#DATATYPE-NUMERIC-TABLE) have exactly the same range, so no problem there. I was referring to the autoincrement  property - essentially the ids will be generated automatically by the DB (see [here](http://www.postgresql.org/docs/9.4/interactive/datatype-numeric.html#DATATYPE-SERIAL)).

Does you second comment mean you agree to implement all entities, the submission registry points to, as independent tables? To be honest I don't see an alternative.

Out of curiosity, does HCC even support primary keys (without extra trigger magic)? If you cannot ensure label is unique, how would you do it for archiveId?

**Comment by Marfroem** [comment]
The HCC have primaryKeys but not in the dynamic cellcontent area. We can skype on Monday or Tuesday. I think in a direct talk it's moore clearly, what I mean.

**Comment by Marfroem** [comment]
then i can explain the conection between the HCC and all other entitys too

**Comment by ikostadi** [comment]
I guess what we need to complete this is:
* data_provider entity
* user/person entity

@Marfroem, please confirm.

**Comment by Marfroem** [comment]
currently I work on this tables,
and some other tables like dataprovider_persistentidentfier.

It will be ready today

**Pull request merged**
